### ISSUE TITLE
DumpChr Problem

### ISSUE THREAD

**Issue by ghost** [cyneprepou4uk/BZK-6502-Disassembler#1]
Reading bytes from <game.nes> file...
Reading bytes from <game.cdl> file...
Dumping header into <header.bin> file...
Dumping CHR into <CHR_ROM.chr> file...
lua53.exe: C:\BZK 6502\functions.lua:80: bad argument #1 to 'write' (string expected, got nil)
stack traceback:
        [C]: in function 'io.write'
        C:\BZK 6502\functions.lua:80: in function 'DumpChr'
        disassembler.lua:10: in main chunk
        [C]: in ?

**Comment by cyneprepou4uk** [comment]
You need to properly specify CHR_file "base ROM file address" and "size" in config.lua file

**Comment by ghost** [comment]
I think you should implement a NES 2.0 header database with a choice to use it or not.

**Comment by ghost** [comment]
Plus I did specify the CHR ROM offset and the size , I used the ROM Nuts&Milk just to test since it's a very basic ROM, CHR is at 0x4010 , size one bank 8K

**Comment by ghost** [comment]
Since it also dump correctly the CHR
![image](https://user-images.githubusercontent.com/37517008/101938477-ad893f00-3be3-11eb-8a0b-30fdd7ba3a3a.png)

**Comment by cyneprepou4uk** [comment]
For Nuts & MIlk you need these options:Attach an archieve with all your input files + config.lua

**Comment by cyneprepou4uk** [comment]
For Nuts & Milk (J) [!].nes you need this options:


`CHR_file = { "CHR_ROM.chr", 0x004010, 0x2000 }`



```
ASM_config_table = 
    {
        "bank_00.asm", 0x000010, 0xC000, 0x4000, "game.tbl",
    }
```


If you still have troubles, attach an archieve will all your files from C:\BZK 6502

**Comment by ghost** [comment]
It works with the 0x2000
~~Well I though the size is the real size , it turned out to be the number of CHR banks.~~
0x2000 = 8192 bytes

**Comment by cyneprepou4uk** [comment]
Speaking of this game, I've made a disassembly of it myself, if you're interested.
https://github.com/cyneprepou4uk/NES-Games-Disassembly
