### ISSUE TITLE
Script issue with the latest version of Notepad++ (v8.4.8), LuaScript Plugin v0.12

### ISSUE THREAD

**Issue by palaceswitcher** [cyneprepou4uk/BZK-6502-Disassembler#3]
Toggling words to use labels in the Lua scripts prompts this error in the Lua console and prevents the user from adding labels to pointers.
```
File:202: bad argument #1 to 'find' (string expected, got nil)
stack traceback:
	[C]: in function 'string.find'
	File:202: in function <File:200>
```

**Comment by cyneprepou4uk** [comment]
Line 202, try to replace
`if size == 0 or string.find(text, "\n") ~= nil then`
with
`if size == 0 or size == nil or string.find(text, "\n") ~= nil then`

Then restart the program.

If the problem still occurs, or other functions prompts similar errors, switch to 8.2.1 Notepad++ version with 0.11 LusScript plugin version. I probably won't be supporting newer versions for a while now.
